version: "3.7"

services:
    mysql:
        image: mysql:8.0.20
        container_name: "HintSys-mysql"
        restart: unless-stopped
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        cap_add:
            - SYS_NICE
    app:
        container_name: "HintSys-app"
        restart: unless-stopped
        depends_on:
            - mysql
        build:
            context: ./app
        ports:
            - "${MOCKSAT_PORT}:3001"
        volumes:
            - ./app/public:/app/public
        environment:
            DB_PASS: ${MYSQL_ROOT_PASSWORD}
            NODE_ENV: "production"

volumes:
    mysql-volume:
